# Generated by Django 6.0.2 on 2026-03-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('college', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('jdate', models.CharField(max_length=30, null=True)),
                ('tfee', models.CharField(max_length=30, null=True)),
                ('pfee', models.CharField(max_length=30, null=True)),
                ('lfee', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('technology', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
