# Generated by Django 6.0.2 on 2026-04-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='jdate',
            new_name='joining_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lfee',
            new_name='left_fee',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pfee',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='paid_fee',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tfee',
            new_name='total_fee',
        ),
    ]
